#!/bin/bash

function join {
	echo "$*" | sed 's/ /, /g'
}

vpn=$( ip addr show ppp0 | grep -oP 'inet \K\d{1,3}(\.\d{1,3}){3}' )
wifi=$( ip addr show wlp2s0 | grep -oP 'inet \K\d{1,3}(\.\d{1,3}){3}' )
wired=$( ip addr show enp1s0f0 | grep -oP 'inet \K\d{1,3}(\.\d{1,3}){3}' )

echo $( join $vpn $wifi $wired )

