#!/bin/bash

mod=$(( $(date +%-S) % 5 ))

date_aymd=$( date -d "-4 hours -$mod sec" +%a\ %F )
date_h=$(( $(date -d "-4 hours -$mod sec" +%-H) + 4 ))
date_ms=$( date -d "-$mod sec" +%M:%S )

date_h=$( printf "%02d" $date_h )

echo "$date_aymd $date_h:$date_ms "
